name: Deploy to Production

on:
  workflow_run:
    workflows: ["main.yml"]
    branches:
      - main
    types:
      - completed

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myproject-name:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myproject-name:${{ github.sha }}